# flake8: noqa

"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.21
    Generated by: https://openapi-generator.tech
"""


__version__ = "1.21"

# import ApiClient
from osis_reference_sdk.api_client import ApiClient

# import Configuration
from osis_reference_sdk.configuration import Configuration

# import exceptions
from osis_reference_sdk.exceptions import OpenApiException
from osis_reference_sdk.exceptions import ApiAttributeError
from osis_reference_sdk.exceptions import ApiTypeError
from osis_reference_sdk.exceptions import ApiValueError
from osis_reference_sdk.exceptions import ApiKeyError
from osis_reference_sdk.exceptions import ApiException
