"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.student_affectation_get import StudentAffectationGet
globals()['StudentAffectationGet'] = StudentAffectationGet
from osis_reference_sdk.model.student_affectation_paging import StudentAffectationPaging


class TestStudentAffectationPaging(unittest.TestCase):
    """StudentAffectationPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudentAffectationPaging(self):
        """Test StudentAffectationPaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudentAffectationPaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
