"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.approuver_proposition_command import ApprouverPropositionCommand


class TestApprouverPropositionCommand(unittest.TestCase):
    """ApprouverPropositionCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testApprouverPropositionCommand(self):
        """Test ApprouverPropositionCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ApprouverPropositionCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
