"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.student_get import StudentGet
globals()['StudentGet'] = StudentGet
from osis_reference_sdk.model.student_paging import StudentPaging


class TestStudentPaging(unittest.TestCase):
    """StudentPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudentPaging(self):
        """Test StudentPaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudentPaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
