"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.score_list_get import ScoreListGet


class TestScoreListGet(unittest.TestCase):
    """ScoreListGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScoreListGet(self):
        """Test ScoreListGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScoreListGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
