"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.country import Country
globals()['Country'] = Country
from osis_reference_sdk.model.paginated_country_all_of import PaginatedCountryAllOf


class TestPaginatedCountryAllOf(unittest.TestCase):
    """PaginatedCountryAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedCountryAllOf(self):
        """Test PaginatedCountryAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedCountryAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
