"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.23
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.cycle_enum import CycleEnum


class TestCycleEnum(unittest.TestCase):
    """CycleEnum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCycleEnum(self):
        """Test CycleEnum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CycleEnum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
