"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.allocation_get import AllocationGet
globals()['AllocationGet'] = AllocationGet
from osis_reference_sdk.model.allocation_paging import AllocationPaging


class TestAllocationPaging(unittest.TestCase):
    """AllocationPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAllocationPaging(self):
        """Test AllocationPaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = AllocationPaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
