"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.cohort_get import CohortGet
from osis_reference_sdk.model.specialty_get import SpecialtyGet
globals()['CohortGet'] = CohortGet
globals()['SpecialtyGet'] = SpecialtyGet
from osis_reference_sdk.model.internship_get import InternshipGet


class TestInternshipGet(unittest.TestCase):
    """InternshipGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testInternshipGet(self):
        """Test InternshipGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = InternshipGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
