"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.diploma_results import DiplomaResults
from osis_reference_sdk.model.equivalence import Equivalence
from osis_reference_sdk.model.foreign_diploma_types import ForeignDiplomaTypes
globals()['DiplomaResults'] = DiplomaResults
globals()['Equivalence'] = Equivalence
globals()['ForeignDiplomaTypes'] = ForeignDiplomaTypes
from osis_reference_sdk.model.high_school_diploma_foreign_diploma import HighSchoolDiplomaForeignDiploma


class TestHighSchoolDiplomaForeignDiploma(unittest.TestCase):
    """HighSchoolDiplomaForeignDiploma unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHighSchoolDiplomaForeignDiploma(self):
        """Test HighSchoolDiplomaForeignDiploma"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HighSchoolDiplomaForeignDiploma()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
