"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.26
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.paginated_superior_non_university_all_of import PaginatedSuperiorNonUniversityAllOf
from osis_reference_sdk.model.paging import Paging
from osis_reference_sdk.model.superior_non_university import SuperiorNonUniversity
globals()['PaginatedSuperiorNonUniversityAllOf'] = PaginatedSuperiorNonUniversityAllOf
globals()['Paging'] = Paging
globals()['SuperiorNonUniversity'] = SuperiorNonUniversity
from osis_reference_sdk.model.paginated_superior_non_university import PaginatedSuperiorNonUniversity


class TestPaginatedSuperiorNonUniversity(unittest.TestCase):
    """PaginatedSuperiorNonUniversity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedSuperiorNonUniversity(self):
        """Test PaginatedSuperiorNonUniversity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedSuperiorNonUniversity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
