"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.24
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.diploma import Diploma
globals()['Diploma'] = Diploma
from osis_reference_sdk.model.paginated_diploma_all_of import PaginatedDiplomaAllOf


class TestPaginatedDiplomaAllOf(unittest.TestCase):
    """PaginatedDiplomaAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedDiplomaAllOf(self):
        """Test PaginatedDiplomaAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedDiplomaAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
