"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.admission_type import AdmissionType
from osis_reference_sdk.model.choix_commission_proximite import ChoixCommissionProximite
from osis_reference_sdk.model.choix_doctorat_deja_realise import ChoixDoctoratDejaRealise
from osis_reference_sdk.model.choix_langue_redaction_these import ChoixLangueRedactionThese
globals()['AdmissionType'] = AdmissionType
globals()['ChoixCommissionProximite'] = ChoixCommissionProximite
globals()['ChoixDoctoratDejaRealise'] = ChoixDoctoratDejaRealise
globals()['ChoixLangueRedactionThese'] = ChoixLangueRedactionThese
from osis_reference_sdk.model.completer_proposition_command import CompleterPropositionCommand


class TestCompleterPropositionCommand(unittest.TestCase):
    """CompleterPropositionCommand unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompleterPropositionCommand(self):
        """Test CompleterPropositionCommand"""
        # FIXME: construct object with mandatory attributes with example values
        # model = CompleterPropositionCommand()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
