"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.score_get import ScoreGet
globals()['ScoreGet'] = ScoreGet
from osis_reference_sdk.model.score_paging import ScorePaging


class TestScorePaging(unittest.TestCase):
    """ScorePaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testScorePaging(self):
        """Test ScorePaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ScorePaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
