"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.academic_partner_type_enum import AcademicPartnerTypeEnum
from osis_reference_sdk.model.organization_type_enum import OrganizationTypeEnum
globals()['AcademicPartnerTypeEnum'] = AcademicPartnerTypeEnum
globals()['OrganizationTypeEnum'] = OrganizationTypeEnum
from osis_reference_sdk.model.organization import Organization


class TestOrganization(unittest.TestCase):
    """Organization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganization(self):
        """Test Organization"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Organization()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
