"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_reference_sdk
from osis_reference_sdk.api.autocomplete_api import AutocompleteApi  # noqa: E501


class TestAutocompleteApi(unittest.TestCase):
    """AutocompleteApi unit test stubs"""

    def setUp(self):
        self.api = AutocompleteApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_list_doctorat_dtos(self):
        """Test case for list_doctorat_dtos

        """
        pass

    def test_list_persons(self):
        """Test case for list_persons

        """
        pass

    def test_list_sector_dtos(self):
        """Test case for list_sector_dtos

        """
        pass

    def test_list_tutors(self):
        """Test case for list_tutors

        """
        pass


if __name__ == '__main__':
    unittest.main()
