"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.city import City
globals()['City'] = City
from osis_reference_sdk.model.paginated_city_all_of import PaginatedCityAllOf


class TestPaginatedCityAllOf(unittest.TestCase):
    """PaginatedCityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedCityAllOf(self):
        """Test PaginatedCityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedCityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
