"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_reference_sdk
from osis_reference_sdk.api.organizations_api import OrganizationsApi  # noqa: E501


class TestOrganizationsApi(unittest.TestCase):
    """OrganizationsApi unit test stubs"""

    def setUp(self):
        self.api = OrganizationsApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_organizations_history_list(self):
        """Test case for organizations_history_list

        """
        pass

    def test_organizations_list(self):
        """Test case for organizations_list

        """
        pass

    def test_organizations_search_duplicate(self):
        """Test case for organizations_search_duplicate

        """
        pass


if __name__ == '__main__':
    unittest.main()
