"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.20
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.study_domain import StudyDomain
globals()['StudyDomain'] = StudyDomain
from osis_reference_sdk.model.paginated_study_domain_all_of import PaginatedStudyDomainAllOf


class TestPaginatedStudyDomainAllOf(unittest.TestCase):
    """PaginatedStudyDomainAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedStudyDomainAllOf(self):
        """Test PaginatedStudyDomainAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedStudyDomainAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
