"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.actor_type import ActorType
globals()['ActorType'] = ActorType
from osis_reference_sdk.model.supervision_actor import SupervisionActor


class TestSupervisionActor(unittest.TestCase):
    """SupervisionActor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSupervisionActor(self):
        """Test SupervisionActor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SupervisionActor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
