"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.26
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.superior_non_university_detail_all_of import SuperiorNonUniversityDetailAllOf


class TestSuperiorNonUniversityDetailAllOf(unittest.TestCase):
    """SuperiorNonUniversityDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuperiorNonUniversityDetailAllOf(self):
        """Test SuperiorNonUniversityDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuperiorNonUniversityDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
