"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.language import Language


class TestLanguage(unittest.TestCase):
    """Language unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguage(self):
        """Test Language"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Language()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
