"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.doctorat_dto import DoctoratDTO


class TestDoctoratDTO(unittest.TestCase):
    """DoctoratDTO unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDoctoratDTO(self):
        """Test DoctoratDTO"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DoctoratDTO()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
