"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.22
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.city import City
from osis_reference_sdk.model.paginated_city_all_of import PaginatedCityAllOf
from osis_reference_sdk.model.paging import Paging
globals()['City'] = City
globals()['PaginatedCityAllOf'] = PaginatedCityAllOf
globals()['Paging'] = Paging
from osis_reference_sdk.model.paginated_city import PaginatedCity


class TestPaginatedCity(unittest.TestCase):
    """PaginatedCity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedCity(self):
        """Test PaginatedCity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedCity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
