"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.action_link import ActionLink
from osis_reference_sdk.model.organization import Organization
from osis_reference_sdk.model.paginated_organization_all_of import PaginatedOrganizationAllOf
from osis_reference_sdk.model.paging import Paging
globals()['ActionLink'] = ActionLink
globals()['Organization'] = Organization
globals()['PaginatedOrganizationAllOf'] = PaginatedOrganizationAllOf
globals()['Paging'] = Paging
from osis_reference_sdk.model.paginated_organization import PaginatedOrganization


class TestPaginatedOrganization(unittest.TestCase):
    """PaginatedOrganization unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedOrganization(self):
        """Test PaginatedOrganization"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedOrganization()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
