"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.tutor import Tutor


class TestTutor(unittest.TestCase):
    """Tutor unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testTutor(self):
        """Test Tutor"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Tutor()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
