"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.organization_duplicate import OrganizationDuplicate
globals()['OrganizationDuplicate'] = OrganizationDuplicate
from osis_reference_sdk.model.organization_duplicate_score_list import OrganizationDuplicateScoreList


class TestOrganizationDuplicateScoreList(unittest.TestCase):
    """OrganizationDuplicateScoreList unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationDuplicateScoreList(self):
        """Test OrganizationDuplicateScoreList"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganizationDuplicateScoreList()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
