"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.24
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.high_school import HighSchool
globals()['HighSchool'] = HighSchool
from osis_reference_sdk.model.paginated_high_school_all_of import PaginatedHighSchoolAllOf


class TestPaginatedHighSchoolAllOf(unittest.TestCase):
    """PaginatedHighSchoolAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedHighSchoolAllOf(self):
        """Test PaginatedHighSchoolAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedHighSchoolAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
