"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.23
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.cycle_enum import CycleEnum
from osis_reference_sdk.model.duration_type_enum import DurationTypeEnum
from osis_reference_sdk.model.study_type_enum import StudyTypeEnum
globals()['CycleEnum'] = CycleEnum
globals()['DurationTypeEnum'] = DurationTypeEnum
globals()['StudyTypeEnum'] = StudyTypeEnum
from osis_reference_sdk.model.diploma_detail_all_of import DiplomaDetailAllOf


class TestDiplomaDetailAllOf(unittest.TestCase):
    """DiplomaDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testDiplomaDetailAllOf(self):
        """Test DiplomaDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = DiplomaDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
