"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.educational_type import EducationalType


class TestEducationalType(unittest.TestCase):
    """EducationalType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testEducationalType(self):
        """Test EducationalType"""
        # FIXME: construct object with mandatory attributes with example values
        # model = EducationalType()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
