"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.superior_non_university import SuperiorNonUniversity
from osis_reference_sdk.model.superior_non_university_detail_all_of import SuperiorNonUniversityDetailAllOf
globals()['SuperiorNonUniversity'] = SuperiorNonUniversity
globals()['SuperiorNonUniversityDetailAllOf'] = SuperiorNonUniversityDetailAllOf
from osis_reference_sdk.model.superior_non_university_detail import SuperiorNonUniversityDetail


class TestSuperiorNonUniversityDetail(unittest.TestCase):
    """SuperiorNonUniversityDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSuperiorNonUniversityDetail(self):
        """Test SuperiorNonUniversityDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SuperiorNonUniversityDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
