"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.person_affectation_get import PersonAffectationGet
globals()['PersonAffectationGet'] = PersonAffectationGet
from osis_reference_sdk.model.person_affectation_paging import PersonAffectationPaging


class TestPersonAffectationPaging(unittest.TestCase):
    """PersonAffectationPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPersonAffectationPaging(self):
        """Test PersonAffectationPaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PersonAffectationPaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
