"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.language import Language
globals()['Language'] = Language
from osis_reference_sdk.model.paginated_language_all_of import PaginatedLanguageAllOf


class TestPaginatedLanguageAllOf(unittest.TestCase):
    """PaginatedLanguageAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedLanguageAllOf(self):
        """Test PaginatedLanguageAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedLanguageAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
