"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.organization import Organization
from osis_reference_sdk.model.paginated_organization_history_all_of import PaginatedOrganizationHistoryAllOf
from osis_reference_sdk.model.paging import Paging
globals()['Organization'] = Organization
globals()['PaginatedOrganizationHistoryAllOf'] = PaginatedOrganizationHistoryAllOf
globals()['Paging'] = Paging
from osis_reference_sdk.model.paginated_organization_history import PaginatedOrganizationHistory


class TestPaginatedOrganizationHistory(unittest.TestCase):
    """PaginatedOrganizationHistory unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedOrganizationHistory(self):
        """Test PaginatedOrganizationHistory"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedOrganizationHistory()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
