"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.student import Student


class TestStudent(unittest.TestCase):
    """Student unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudent(self):
        """Test Student"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Student()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
