"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.26
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.paginated_study_domain_all_of import PaginatedStudyDomainAllOf
from osis_reference_sdk.model.paging import Paging
from osis_reference_sdk.model.study_domain import StudyDomain
globals()['PaginatedStudyDomainAllOf'] = PaginatedStudyDomainAllOf
globals()['Paging'] = Paging
globals()['StudyDomain'] = StudyDomain
from osis_reference_sdk.model.paginated_study_domain import PaginatedStudyDomain


class TestPaginatedStudyDomain(unittest.TestCase):
    """PaginatedStudyDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedStudyDomain(self):
        """Test PaginatedStudyDomain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedStudyDomain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
