"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.action_link import ActionLink


class TestActionLink(unittest.TestCase):
    """ActionLink unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testActionLink(self):
        """Test ActionLink"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ActionLink()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
