"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.language import Language
from osis_reference_sdk.model.paginated_language_all_of import PaginatedLanguageAllOf
from osis_reference_sdk.model.paging import Paging
globals()['Language'] = Language
globals()['PaginatedLanguageAllOf'] = PaginatedLanguageAllOf
globals()['Paging'] = Paging
from osis_reference_sdk.model.paginated_language import PaginatedLanguage


class TestPaginatedLanguage(unittest.TestCase):
    """PaginatedLanguage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedLanguage(self):
        """Test PaginatedLanguage"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedLanguage()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
