"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.high_school_diploma_belgian_diploma import HighSchoolDiplomaBelgianDiploma
from osis_reference_sdk.model.high_school_diploma_foreign_diploma import HighSchoolDiplomaForeignDiploma
globals()['HighSchoolDiplomaBelgianDiploma'] = HighSchoolDiplomaBelgianDiploma
globals()['HighSchoolDiplomaForeignDiploma'] = HighSchoolDiplomaForeignDiploma
from osis_reference_sdk.model.high_school_diploma import HighSchoolDiploma


class TestHighSchoolDiploma(unittest.TestCase):
    """HighSchoolDiploma unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHighSchoolDiploma(self):
        """Test HighSchoolDiploma"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HighSchoolDiploma()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
