"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.27
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_reference_sdk
from osis_reference_sdk.api.universities_api import UniversitiesApi  # noqa: E501


class TestUniversitiesApi(unittest.TestCase):
    """UniversitiesApi unit test stubs"""

    def setUp(self):
        self.api = UniversitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_universities_list(self):
        """Test case for universities_list

        """
        pass

    def test_university_read(self):
        """Test case for university_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
