"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.university import University
globals()['University'] = University
from osis_reference_sdk.model.paginated_university_all_of import PaginatedUniversityAllOf


class TestPaginatedUniversityAllOf(unittest.TestCase):
    """PaginatedUniversityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedUniversityAllOf(self):
        """Test PaginatedUniversityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedUniversityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
