"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.27
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.high_school import HighSchool
from osis_reference_sdk.model.high_school_detail_all_of import HighSchoolDetailAllOf
globals()['HighSchool'] = HighSchool
globals()['HighSchoolDetailAllOf'] = HighSchoolDetailAllOf
from osis_reference_sdk.model.high_school_detail import HighSchoolDetail


class TestHighSchoolDetail(unittest.TestCase):
    """HighSchoolDetail unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHighSchoolDetail(self):
        """Test HighSchoolDetail"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HighSchoolDetail()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
