"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.language_knowledge_grade import LanguageKnowledgeGrade
globals()['LanguageKnowledgeGrade'] = LanguageKnowledgeGrade
from osis_reference_sdk.model.language_knowledge import LanguageKnowledge


class TestLanguageKnowledge(unittest.TestCase):
    """LanguageKnowledge unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testLanguageKnowledge(self):
        """Test LanguageKnowledge"""
        # FIXME: construct object with mandatory attributes with example values
        # model = LanguageKnowledge()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
