"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.27
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.university_detail_all_of import UniversityDetailAllOf


class TestUniversityDetailAllOf(unittest.TestCase):
    """UniversityDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testUniversityDetailAllOf(self):
        """Test UniversityDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = UniversityDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
