"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.24
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.high_school_detail_all_of import HighSchoolDetailAllOf


class TestHighSchoolDetailAllOf(unittest.TestCase):
    """HighSchoolDetailAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testHighSchoolDetailAllOf(self):
        """Test HighSchoolDetailAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = HighSchoolDetailAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
