"""
    Admission API

    This API delivers data for the Admission project.  # noqa: E501

    The version of the OpenAPI document: 1.0.4
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.action_link import ActionLink
globals()['ActionLink'] = ActionLink
from osis_reference_sdk.model.proposition_search_links import PropositionSearchLinks


class TestPropositionSearchLinks(unittest.TestCase):
    """PropositionSearchLinks unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPropositionSearchLinks(self):
        """Test PropositionSearchLinks"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PropositionSearchLinks()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
