"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.superior_non_university import SuperiorNonUniversity
globals()['SuperiorNonUniversity'] = SuperiorNonUniversity
from osis_reference_sdk.model.paginated_superior_non_university_all_of import PaginatedSuperiorNonUniversityAllOf


class TestPaginatedSuperiorNonUniversityAllOf(unittest.TestCase):
    """PaginatedSuperiorNonUniversityAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedSuperiorNonUniversityAllOf(self):
        """Test PaginatedSuperiorNonUniversityAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedSuperiorNonUniversityAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
