"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.19
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.academic_calendar import AcademicCalendar
globals()['AcademicCalendar'] = AcademicCalendar
from osis_reference_sdk.model.paginated_academic_calendars_all_of import PaginatedAcademicCalendarsAllOf


class TestPaginatedAcademicCalendarsAllOf(unittest.TestCase):
    """PaginatedAcademicCalendarsAllOf unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedAcademicCalendarsAllOf(self):
        """Test PaginatedAcademicCalendarsAllOf"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedAcademicCalendarsAllOf()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
