"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.28
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.paginated_university_all_of import PaginatedUniversityAllOf
from osis_reference_sdk.model.paging import Paging
from osis_reference_sdk.model.university import University
globals()['PaginatedUniversityAllOf'] = PaginatedUniversityAllOf
globals()['Paging'] = Paging
globals()['University'] = University
from osis_reference_sdk.model.paginated_university import PaginatedUniversity


class TestPaginatedUniversity(unittest.TestCase):
    """PaginatedUniversity unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedUniversity(self):
        """Test PaginatedUniversity"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedUniversity()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
