"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.22
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.diploma import Diploma
from osis_reference_sdk.model.paginated_diploma_all_of import PaginatedDiplomaAllOf
from osis_reference_sdk.model.paging import Paging
globals()['Diploma'] = Diploma
globals()['PaginatedDiplomaAllOf'] = PaginatedDiplomaAllOf
globals()['Paging'] = Paging
from osis_reference_sdk.model.paginated_diploma import PaginatedDiploma


class TestPaginatedDiploma(unittest.TestCase):
    """PaginatedDiploma unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedDiploma(self):
        """Test PaginatedDiploma"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedDiploma()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
