"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.specialty_get import SpecialtyGet
globals()['SpecialtyGet'] = SpecialtyGet
from osis_reference_sdk.model.specialty_paging import SpecialtyPaging


class TestSpecialtyPaging(unittest.TestCase):
    """SpecialtyPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSpecialtyPaging(self):
        """Test SpecialtyPaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = SpecialtyPaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
