"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.12
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.language import Language
globals()['Language'] = Language
from osis_reference_sdk.model.array_of_languages import ArrayOfLanguages


class TestArrayOfLanguages(unittest.TestCase):
    """ArrayOfLanguages unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testArrayOfLanguages(self):
        """Test ArrayOfLanguages"""
        # FIXME: construct object with mandatory attributes with example values
        # model = ArrayOfLanguages()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
