"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.26
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.study_domain import StudyDomain


class TestStudyDomain(unittest.TestCase):
    """StudyDomain unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStudyDomain(self):
        """Test StudyDomain"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StudyDomain()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
