"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.organization_get import OrganizationGet
globals()['OrganizationGet'] = OrganizationGet
from osis_reference_sdk.model.organization_paging import OrganizationPaging


class TestOrganizationPaging(unittest.TestCase):
    """OrganizationPaging unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testOrganizationPaging(self):
        """Test OrganizationPaging"""
        # FIXME: construct object with mandatory attributes with example values
        # model = OrganizationPaging()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
