"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.high_school import HighSchool
from osis_reference_sdk.model.paginated_high_school_all_of import PaginatedHighSchoolAllOf
from osis_reference_sdk.model.paging import Paging
globals()['HighSchool'] = HighSchool
globals()['PaginatedHighSchoolAllOf'] = PaginatedHighSchoolAllOf
globals()['Paging'] = Paging
from osis_reference_sdk.model.paginated_high_school import PaginatedHighSchool


class TestPaginatedHighSchool(unittest.TestCase):
    """PaginatedHighSchool unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testPaginatedHighSchool(self):
        """Test PaginatedHighSchool"""
        # FIXME: construct object with mandatory attributes with example values
        # model = PaginatedHighSchool()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
