"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_reference_sdk
from osis_reference_sdk.api.internship_api import InternshipApi  # noqa: E501


class TestInternshipApi(unittest.TestCase):
    """InternshipApi unit test stubs"""

    def setUp(self):
        self.api = InternshipApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_cohorts_get(self):
        """Test case for cohorts_get

        """
        pass

    def test_cohorts_uuid_get(self):
        """Test case for cohorts_uuid_get

        """
        pass

    def test_internships_get(self):
        """Test case for internships_get

        """
        pass

    def test_internships_uuid_get(self):
        """Test case for internships_uuid_get

        """
        pass

    def test_masters_allocations_get(self):
        """Test case for masters_allocations_get

        """
        pass

    def test_masters_allocations_post(self):
        """Test case for masters_allocations_post

        """
        pass

    def test_masters_allocations_uuid_delete(self):
        """Test case for masters_allocations_uuid_delete

        """
        pass

    def test_masters_allocations_uuid_get(self):
        """Test case for masters_allocations_uuid_get

        """
        pass

    def test_masters_get(self):
        """Test case for masters_get

        """
        pass

    def test_masters_post(self):
        """Test case for masters_post

        """
        pass

    def test_masters_uuid_activate_account_post(self):
        """Test case for masters_uuid_activate_account_post

        """
        pass

    def test_masters_uuid_allocations_get(self):
        """Test case for masters_uuid_allocations_get

        """
        pass

    def test_masters_uuid_get(self):
        """Test case for masters_uuid_get

        """
        pass

    def test_organizations_get(self):
        """Test case for organizations_get

        """
        pass

    def test_organizations_uuid_get(self):
        """Test case for organizations_uuid_get

        """
        pass

    def test_periods_get(self):
        """Test case for periods_get

        """
        pass

    def test_periods_uuid_get(self):
        """Test case for periods_uuid_get

        """
        pass

    def test_person_affectations_cohort_person_uuid_get(self):
        """Test case for person_affectations_cohort_person_uuid_get

        """
        pass

    def test_place_evaluation_affectation_uuid_get(self):
        """Test case for place_evaluation_affectation_uuid_get

        """
        pass

    def test_place_evaluation_affectation_uuid_put(self):
        """Test case for place_evaluation_affectation_uuid_put

        """
        pass

    def test_place_evaluation_items_cohort_get(self):
        """Test case for place_evaluation_items_cohort_get

        """
        pass

    def test_scores_affectation_uuid_get(self):
        """Test case for scores_affectation_uuid_get

        """
        pass

    def test_scores_affectation_uuid_put(self):
        """Test case for scores_affectation_uuid_put

        """
        pass

    def test_scores_affectation_uuid_validate_post(self):
        """Test case for scores_affectation_uuid_validate_post

        """
        pass

    def test_specialties_get(self):
        """Test case for specialties_get

        """
        pass

    def test_specialties_uuid_get(self):
        """Test case for specialties_uuid_get

        """
        pass

    def test_students_affectations_affectation_uuid_get(self):
        """Test case for students_affectations_affectation_uuid_get

        """
        pass

    def test_students_affectations_specialty_organization_get(self):
        """Test case for students_affectations_specialty_organization_get

        """
        pass

    def test_students_affectations_specialty_organization_stats_get(self):
        """Test case for students_affectations_specialty_organization_stats_get

        """
        pass

    def test_students_get(self):
        """Test case for students_get

        """
        pass

    def test_students_uuid_get(self):
        """Test case for students_uuid_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
