"""
    Internship API

    This API delivers data for the Internship project.  # noqa: E501

    The version of the OpenAPI document: 1.1.11
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.person import Person
globals()['Person'] = Person
from osis_reference_sdk.model.master_get import MasterGet


class TestMasterGet(unittest.TestCase):
    """MasterGet unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testMasterGet(self):
        """Test MasterGet"""
        # FIXME: construct object with mandatory attributes with example values
        # model = MasterGet()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
