"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.18
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import osis_reference_sdk
from osis_reference_sdk.model.country import Country


class TestCountry(unittest.TestCase):
    """Country unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCountry(self):
        """Test Country"""
        # FIXME: construct object with mandatory attributes with example values
        # model = Country()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
