"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.27
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_reference_sdk
from osis_reference_sdk.api.superior_non_universities_api import SuperiorNonUniversitiesApi  # noqa: E501


class TestSuperiorNonUniversitiesApi(unittest.TestCase):
    """SuperiorNonUniversitiesApi unit test stubs"""

    def setUp(self):
        self.api = SuperiorNonUniversitiesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_superior_non_universities_list(self):
        """Test case for superior_non_universities_list

        """
        pass

    def test_superior_non_university_read(self):
        """Test case for superior_non_university_read

        """
        pass


if __name__ == '__main__':
    unittest.main()
