"""
    Reference Service

    A set of API endpoints that allow you to get reference data.  # noqa: E501

    The version of the OpenAPI document: 1.31
    Generated by: https://openapi-generator.tech
"""


import unittest

import osis_reference_sdk
from osis_reference_sdk.api.languages_api import LanguagesApi  # noqa: E501


class TestLanguagesApi(unittest.TestCase):
    """LanguagesApi unit test stubs"""

    def setUp(self):
        self.api = LanguagesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_languages_list(self):
        """Test case for languages_list

        """
        pass


if __name__ == '__main__':
    unittest.main()
